### ISSUE TITLE
博主的图片哪里搞的，很震撼啊

### ISSUE THREAD

**Issue by ncc0706** [zhisheng17/zhisheng17.github.io#2]

**Comment by zhisheng17** [comment]
什么图片？？

**Comment by zhisheng17** [comment]
你是说每篇博客的图片是吗？下次有个机会写写去哪找这些图片

**Comment by ncc0706** [comment]
博主太给力了，这个也不错 http://bizhi.yeitu.com/chuangyi/20150118_3806.html

**Comment by zhisheng17** [comment]
https://pixabay.com/     @ncc0706   我一般都是这里找的，不需要版权
