### ISSUE TITLE
博主是采用的Yilia的主题自己实现了分类吗？

### ISSUE THREAD

**Issue by ftc300** [zhisheng17/zhisheng17.github.io#3]
![image](https://user-images.githubusercontent.com/12816061/45285249-4e748580-b515-11e8-883e-daf38e0c2a61.png)

**Comment by zhisheng17** [comment]
自己加了个文件夹，把这个博客和随笔指向对应的tags的文章就行

**Comment by ftc300** [comment]
感谢 @zhisheng17
